version: '3.8'

services:
  centrifuge-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-production-secret-key
      - PORT=8080
      - LOG_LEVEL=info
      - CORS_ENABLED=true
      - CORS_ORIGINS=*
    restart: unless-stopped
    
  # Optional: Redis for scaling (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  
  # Optional: PostgreSQL database (uncomment if needed)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: centrifuge_chat
  #     POSTGRES_USER: chatuser
  #     POSTGRES_PASSWORD: chatpass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: